"""
Django settings for {{cookiecutter.project_slug}} project.

Generated by 'django-admin startproject' using Django 1.11.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import sys
import platform
import environ
from datetime import datetime

from django.utils import six

if six.PY2 and sys.getdefaultencoding() == 'ascii':
    import imp
    imp.reload(sys)
    sys.setdefaultencoding('utf-8')


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

env = environ.Env(
    SECRET_KEY=str,
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, ['127.0.0.1:8000']),
    DATABASE_URL=str,
)

"""
if platform.uname()[1].lower().endswith('foo'):
    environ.Env.read_env(os.path.join(BASE_DIR, '../conf/env/.env'))
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = env('DEBUG')
elif platform.uname()[1].lower().endswith('bar'):
    environ.Env.read_env(os.path.join(BASE_DIR, '../conf/env/.env_home'))
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = env('DEBUG')
    ALLOWED_HOSTS = []
    INTERNAL_IPS = ['127.0.0.1', '::1']
else:
    environ.Env.read_env(os.path.join(BASE_DIR, '../conf/env/.env'))
    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = env('DEBUG')
    ALLOWED_HOSTS = env('ALLOWED_HOSTS')
"""

environ.Env.read_env(os.path.join(BASE_DIR, '../../conf/env/.env'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')
ALLOWED_HOSTS = ['ALLOWED_HOSTS']

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# Application definition

INSTALLED_APPS = [
    'xadmin',           # https://github.com/sshwsfc/xadmin
    'crispy_forms',     # https://github.com/django-crispy-forms/django-crispy-forms
    'reversion',        # https://github.com/etianen/django-reversion

    '{{cookiecutter.project_slug}}.base',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django.contrib.sites',
    'django.contrib.humanize',

    # 'captcha'             # https://github.com/praekelt/django-recaptcha
    'django_user_agents',   # https://github.com/selwin/django-user_agents
    'django_mathjax',       # https://github.com/kaleidos/django-mathjax
    # 'debug_toolbar',      # https://github.com/jazzband/django-debug-toolbar
    'djangobower',          # https://github.com/nvbn/django-bower
    'django_extensions',    # https://github.com/django-extensions/django-extensions
    'multiselectfield',     # https://github.com/goinnn/django-multiselectfield
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_user_agents.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = '{{cookiecutter.project_slug}}.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates/')],
        # 'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
            ],
            'loaders': [
                'django.template.loaders.filesystem.Loader',
                'django.template.loaders.app_directories.Loader',
            ],
        },
    },
]

WSGI_APPLICATION = '{{cookiecutter.project_slug}}.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': env.db(),
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = (
    ('en', 'English'),
    ('zh-hans', 'Chinese'),
)

TIME_ZONE = '{{ cookiecutter.timezone }}'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

# this is the *URL* for static files
STATIC_URL = '/static/'

# this is where Django *looks for* static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# this is where static files are *collected*
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
]

BOWER_COMPONENTS_ROOT = os.path.join(BASE_DIR, "")

BOWER_INSTALLED_APPS = (
    'jquery#1.12.4',
    # 'jquery-ui#~1.12.1',
    # 'd3#3.3.6',
    # 'nvd3#1.1.12-beta',
    'bootstrap#3.3.7',                      # --> default bootstrap
    {% if cookiecutter.use_bootswatch == 'y' %}'bootswatch-dist#3.3.7-{{ cookiecutter.bootswatch_theme }}',       # https://bootswatch.com/3/{{ cookiecutter.bootswatch_theme }}/{% endif %}
    # 'bootswatch-dist#3.3.7-amelia',       # https://bootswatch.com/3/amelia/
    # 'bootswatch-dist#3.3.7-cerulean',     # https://bootswatch.com/3/cerulean/
    # 'bootswatch-dist#3.3.7-cosmo',        # https://bootswatch.com/3/cosmo/
    # 'bootswatch-dist#3.3.7-cyborg',       # https://bootswatch.com/3/cyborg/
    # 'bootswatch-dist#3.3.7-darkly',       # https://bootswatch.com/3/darkly/
    # 'bootswatch-dist#3.3.7-flatly',       # https://bootswatch.com/3/flatly/
    # 'bootswatch-dist#3.3.7-journal',      # https://bootswatch.com/3/journal/
    # 'bootswatch-dist#3.3.7-lumen',        # https://bootswatch.com/3/lumen/
    # 'bootswatch-dist#3.3.7-paper',        # https://bootswatch.com/3/paper/
    # 'bootswatch-dist#3.3.7-readable',     # https://bootswatch.com/3/readable/
    # 'bootswatch-dist#3.3.7-sandstone',    # https://bootswatch.com/3/sandstone/
    # 'bootswatch-dist#3.3.7-simplex',      # https://bootswatch.com/3/simplex/
    # 'bootswatch-dist#3.3.7-slate',        # https://bootswatch.com/3/slate/
    # 'bootswatch-dist#3.3.7-solar',        # https://bootswatch.com/3/solar/
    # 'bootswatch-dist#3.3.7-spacelab',     # https://bootswatch.com/3/spacelab/
    # 'bootswatch-dist#3.3.7-superhero',    # https://bootswatch.com/3/superhero/
    # 'bootswatch-dist#3.3.7-united',       # https://bootswatch.com/3/united/
    # 'bootswatch-dist#3.3.7-yeti'          # https://bootswatch.com/3/yeti/
    'fontawesome#4.7.0',
    'MathJax#2.7.2',
    'chartist',
    'masonry',
    'sortable',
)

FILE_UPLOAD_MAX_MEMORY_SIZE = 35000000

# See https://docs.djangoproject.com/en/1.11/ref/settings/#admins
ADMINS = (
    ("""{{cookiecutter.author_name}}""", '{{cookiecutter.email}}'),   # email will be sent to ...
)

MANAGERS = ADMINS

SITE_ID = 1

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# MathJax
MATHJAX_ENABLED = True
MATHJAX_LOCAL_PATH = 'MathJax'

MATHJAX_CONFIG_DATA = {
  "tex2jax": {
    "inlineMath":
      [
          ['$','$'],
          ['\\(','\\)']
      ]
  }
}

